### ISSUE TITLE
Request timeout/Invalid password

### ISSUE THREAD

**Issue by trmendes** [torhve/weechat-matrix-protocol-script#113]
```
matrix: Connecting to homeserver URL: https://matrix.org/
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
request:
  url: https://matrix.org/_matrix/client/r0/login
  post:
    postfields: {"password":"my_password","type":"m.login.password","user":"my_user",
"initial_device_display_name":"WeeMatrix"}
    accept_encoding: application/json
    header: 1
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
reply:
  rc: -2
  command: url:https://matrix.org/_matrix/client/r0/login
  extra:
  stdout:
  stderr:
Call to API errored in command url:https://matrix.org/_matrix/client/r0/login, maybe timeout?
```

This is all I get from Weechat-Matrix

I'm on archlinux, weechat version 2.1, lua 5.3.4, lua-cjson 2.1.0-3

**Comment by trmendes** [comment]
```
request:
  post:
    accept_encoding: application/json
    header: 1
    postfields:
{"password":"my_password","type":"m.login.password","user":"my_email","initial_device_display_name":"WeeMatrix"}
  url: https://matrix.org/_matrix/client/r0/login
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
reply:
  rc: 0
  extra:
  stderr:
  stdout: HTTP/1.1 403 Forbidden
Date: Mon, 07 May 2018 10:53:53 GMT
Content-Type: application/json
Content-Length: 52
Connection: keep-alive
Set-Cookie: __cfduid=xxxxxxxxxxxxxx; expires=Tue, 07-May-19 10:53:52 GMT; path=/; domain=.matrix.org; HttpOnly
Access-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept, Authorization
Cache-Control: no-cache, no-store, must-revalidate
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS
Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
Server: cloudflare
CF-RAY: 417325319afc4b51-GRU

{"errcode":"M_FORBIDDEN","error":"Invalid password"}
  command: url:https://matrix.org/_matrix/client/r0/login
matrix: Error code during login: Invalid password, code: M_FORBIDDEN
matrix: Please verify your username and password
```

It says 

```
{"errcode":"M_FORBIDDEN","error":"Invalid password"}
  command: url:https://matrix.org/_matrix/client/r0/login
matrix: Error code during login: Invalid password, code: M_FORBIDDEN
```

But I'm pretty sure my password isn't wrong.

Any help?
